/**
 * Valli Controller
 *
 * Handles Valli CRUD, resolution, and chain retrieval.
 */

import { asyncHandler, AppError } from '../middleware/errorHandler.js';
import * as valliModel from '../models/valliModel.js';
import * as valliEngine from '../services/valliEngine.js';

/**
 * POST /api/vallis
 * Manually create a Valli (for standalone Vallis not generated by the pipeline).
 */
export const createValli = asyncHandler(async (req, res) => {
  const userId = req.user.id;
  const { activityId, parentValliId, category, title, description, rawScore } = req.body;

  if (!title || !category) {
    throw new AppError('Title and category are required.', 400);
  }

  const valli = await valliEngine.createValli(userId, {
    activityId,
    parentValliId,
    category,
    title,
    description,
    rawScore: rawScore || 5,
  });

  res.status(201).json({
    message: 'Valli created. The chedi grows. 🌿',
    valli,
  });
});

/**
 * GET /api/vallis
 * List all Vallis for the authenticated user.
 */
export const getVallis = asyncHandler(async (req, res) => {
  const userId = req.user.id;
  const { status, category, activityId, limit } = req.query;

  const vallis = await valliModel.findAll(userId, {
    status,
    category,
    activityId,
    limit: limit ? parseInt(limit) : undefined,
  });

  res.json({ vallis, count: vallis.length });
});

/**
 * GET /api/vallis/:id
 * Get a single Valli with its events.
 */
export const getValli = asyncHandler(async (req, res) => {
  const userId = req.user.id;
  const valliId = req.params.id;

  const valli = await valliModel.findById(userId, valliId);
  const events = await valliModel.getEvents(valliId);

  res.json({ valli, events });
});

/**
 * PUT /api/vallis/:id
 * Update a Valli (title, description).
 */
export const updateValli = asyncHandler(async (req, res) => {
  const userId = req.user.id;
  const { title, description } = req.body;

  const valli = await valliModel.update(userId, req.params.id, {
    title,
    description,
  });

  res.json({ message: 'Valli updated.', valli });
});

/**
 * POST /api/vallis/:id/resolve
 * Resolve a Valli. It moves from active to resolved but stays in history.
 */
export const resolveValli = asyncHandler(async (req, res) => {
  const result = await valliEngine.resolveValli(req.user.id, req.params.id);
  res.json(result);
});

/**
 * GET /api/vallis/:id/chain
 * Get the full Valli chain (root + all descendants).
 */
export const getValliChain = asyncHandler(async (req, res) => {
  const chain = await valliEngine.getValliChain(req.user.id, req.params.id);
  res.json(chain);
});
